### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RenatoAugustoIairFigueroaMayta** [demquad/SuxoAU#1]
Hi, with this mod can I identify players who use hacks on PC without being a host?

**Comment by dmmqd** [comment]
Yes, you can identify players using hacks (cheats) without being the host. The host is only needed to take actions against them.

**Comment by RenatoAugustoIairFigueroaMayta** [comment]
Brother help me how to inject the dll?

**Comment by dmmqd** [comment]
**make sure the game is from Steam or Epic Games**

Before launching the game, execute SuxoAULauncher.exe and then launch the game

I recommend adding the folder to your antivirus exclusions list to avoid issues

Alternatively, you can use CheatEngine or ProcessHacker to inject the DLL

**Comment by RenatoAugustoIairFigueroaMayta** [comment]
thanks bro, by the way it doesn't detect players who use malummenu

**Comment by dmmqd** [comment]
The reason it doesn't get detected is because Malum doesn't send RPC. Similarly, SickoMenu and AmongUsMenu do send RPC, which makes them detectable. Suxo also doesn't send RPC, so it's not detectable by other menus.
